' MIT License
' 
' Copyright (c) 2022 Universidad Antonio Nariño
' 
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
' 
' The above copyright notice and this permission notice shall be included in all
' copies or substantial portions of the Software.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
' SOFTWARE.

@startuml uan-spec-engsw-quality-workshop-01-poo

' --- CLASES ---

abstract class Persona {
    -dni:String
    -nombre:String
    -apellidos:String
}

class Administrador {
    -numeroMatriculaProfesional:String
}

class Propietario {
    -direccion:String
    -telefono:String
    -numeroCuentaBancaria:String
}

class Inquilino {
    -telefono:String
}

class MiembroJuntaAdministracion {
    -propiedad:Propiedad
}

class ComunidadVecinos {
    -codigo:String
    -nombre:String
    -calle:String
    -codigoPostal:Integer
    -poblacion:String
    -presidente:MiembroJuntaAdministracion
    -vicepresidente:MiembroJuntaAdministracion
    -vocales:MiembroJuntaAdministracion[]
    -cuentaBancaria:CuentaBancaria
}

class ContratoAdministracion {
    -activo:Boolean
    -comunidadVecinos:ComunidadVecinos
    -administrador:Administrador
    -honorariosAnuales:Double
    -fechaInicio:Date
    -fechaFinal:Date
}

class SectorEmpresaServicio {
    -codigo:String
    -nombre:String
}

class EmpresaServicio {
    -nombre:Stringjunit
    -cif:String
    -direccion:String
    -telefono:String
    -nombrePersonaContacto:String
}

abstract class Propiedad {
    -comunidadVecinos:ComunidadVecinos
    -numeroPredial:Integer
    -planta:String
    -letra:String
    -propietario:Propietario
    -porcentajeParticipacionGastos:Double
    -habitada:Boolean
    -inquilino:Inquilino
}

class PropiedadParticular {
    -numeroHabitaciones:Integer
}

class PropiedadLocalComercial {
    -tipoComercio:String
    -horaInicial:Time
    -horaFinal:Time
}

class PropiedadOficina {
    -actividad:String
}

class Banco {
    -codigo:String
    -nombre:String
    -personaContacto:String
}

class CuentaBancaria {
    -banco:Banco
    -numeroCuenta:String
    -digitoControl1:Integer
    -digitoControl2:Integer
    -saldo:Double
}

abstract class Apunte {
    -numero:String
    -propiedad:Propiedad
    -fecha:Date
    -importe:Double
}

class ReciboAdministracion {
    -cobrado:Boolean
}

class ReciboServicio {
    -empresa:EmpresaServicio
}

' --- MULTIPLICIDAD Y ASOCIACIONES ---

Persona <|-- Administrador

Persona <|-- Propietario

Persona <|-- Inquilino

Persona <|-- MiembroJuntaAdministracion

ComunidadVecinos "1" -- "1..*" ContratoAdministracion

Administrador "1" -- "1..*" ContratoAdministracion

SectorEmpresaServicio "1" -- "1..*" EmpresaServicio

Propietario "1" -- "1..*" Propiedad

Inquilino "0..1" -- "1..*" Propiedad

Propiedad <|-- PropiedadParticular

Propiedad <|-- PropiedadLocalComercial

Propiedad <|-- PropiedadOficina

ComunidadVecinos "1" -- "1" MiembroJuntaAdministracion : presidente

ComunidadVecinos "1" -- "1" MiembroJuntaAdministracion : vicepresidente

ComunidadVecinos "1" *-- "1..*" MiembroJuntaAdministracion : vocales

ComunidadVecinos "1" -- "1..*" Propiedad

Banco "1" -- "1..*" CuentaBancaria

ComunidadVecinos "1" -- "1" CuentaBancaria

Propiedad "1" -- "1..*" ReciboAdministracion : ingresos

Propiedad "1" -- "1..*" ReciboServicio : gastos

Apunte <|-- ReciboAdministracion

Apunte <|-- ReciboServicio

EmpresaServicio "1" -- "1..*" ReciboServicio

@enduml